name: Create Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      LATEST_NODE: 16
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 14, 16, 18 ]
        os_name: [ "slim" ]

    steps:
      - name: 1-checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 2-setup-image-setting
        id: setting
        run: |
          TAGS="ghcr.io/${{ github.repository }}:${{ matrix.node }}"
          if [ "${{ matrix.node }}" == "${{ env.LATEST_NODE }}" ]; then
            TAGS="$TAGS,ghcr.io/${{ github.repository }}:latest"
          fi

          echo $TAGS

          echo "TAGS=$TAGS" >> $GITHUB_ENV
      - name: 3-setup-qemu-action
        uses: docker/setup-qemu-action@v1
      - name: 4-login-action
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 5-setup-buildx-action
        uses: docker/setup-buildx-action@v1
      - name: 6-build-push-action
        uses: docker/build-push-action@v2
        continue-on-error: true
        with:
          context: ./
          file: ./Dockerfile
          platforms: "linux/amd64, linux/arm/v7, linux/arm64"
          push: true
          build-args: |
            OS_NAME=${{ matrix.os_name }}
            NODE_VERSION=${{ matrix.node }}
          tags: |
            ${{ env.TAGS }}