name: Create Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      LATEST_NODE: 16
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 14, 16, 18 ]
        suffix: [ "", "raspberry" ]
        exclude:
          - node: 18
            suffix: raspberry

    steps:
      - name: 1-checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 2-setup-image-setting
        id: setting
        run: |
          SUFFIX=""
          if [ "${{ matrix.suffix }}" != "" ]; then
            SUFFIX="-${{ matrix.suffix}}"
          fi

          TAGS="ghcr.io/${{ github.repository }}:${{ matrix.node }}$SUFFIX"
          if [ "${{ matrix.node }}" == "${{ env.LATEST_NODE }}" ]; then
            TAGS="$TAGS,ghcr.io/${{ github.repository }}:latest$SUFFIX"
          fi

          echo "current tags $TAGS"
          echo "TAGS=$TAGS" >> $GITHUB_ENV

          OS_NAME=""
          PLATFORMS=""
          if [ "${{ matrix.suffix }}" == "" ]; then
            OS_NAME="node:${{ matrix.node }}-bullseye-slim"
            PLATFORMS="linux/amd64, linux/arm64, linux/arm/v7"
          elif [ "${{ matrix.suffix}}" == "raspberry" ]; then
            OS_NAME="balenalib/raspberry-pi-node:${{ matrix.node }}-bullseye"
            PLATFORMS="linux/arm/v6"
          fi

          echo "current OS $OS_NAME"
          echo "OS_NAME=$OS_NAME" >> $GITHUB_ENV

          echo "current platforms $PLATFORMS"
          echo "PLATFORMS=$PLATFORMS" >> $GITHUB_ENV

      - name: 3-setup-qemu-action
        uses: docker/setup-qemu-action@v2
      - name: 4-login-action
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 5-setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: 6-build-push-action
        uses: docker/build-push-action@v3
        continue-on-error: true
        with:
          context: ./
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            OS_NAME=${{ env.OS_NAME }}
          tags: |
            ${{ env.TAGS }}